name: pipelines

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

    

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Artifact
          path: target/*.jar

  development:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Downloading artifact
        uses: actions/download-artifact@v2
        with:
          name: Artifact
          path: target/

      - name: building docker
        run: docker build -t maciekk20012001/pipeline:development -f Dockerfile .

      - name: pushing docker
        run: docker push maciekk20012001/pipeline:development

  production:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Downloading artifact
        uses: actions/download-artifact@v2
        with:
          name: Artifact
          path: target/

      - name: building docker
        run: docker build -t maciekk20012001/pipeline:production -f Dockerfile .

      - name: pushing docker
        run: docker push maciekk20012001/pipeline:production
